#!/bin/bash

# Quick guide for adding Xcode capabilities

echo "📱 Xcode Capabilities - Quick Guide"
echo "===================================="
echo ""
echo "📍 Location in Xcode:"
echo "   1. Left sidebar: Click 'Runner' (blue project icon)"
echo "   2. Main area: Click 'Signing & Capabilities' tab"
echo "   3. Look for: '+ Capability' button"
echo ""
echo "🔍 Finding the Capabilities:"
echo ""
echo "When you click '+ Capability', you'll see a searchable list."
echo "Try searching for:"
echo ""
echo "   For Push Notifications:"
echo "   • Type: 'push'"
echo "   • Look for: 'Push Notifications'"
echo "   • Or: 'Notifications'"
echo ""
echo "   For Background Modes:"
echo "   • Type: 'background'"
echo "   • Look for: 'Background Modes'"
echo "   • Or: 'Background'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Step-by-Step:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. In Xcode, select 'Runner' project (left sidebar)"
echo "2. Select 'Runner' target (under TARGETS)"
echo "3. Click 'Signing & Capabilities' tab"
echo "4. Find '+ Capability' button (usually top-right of Capabilities section)"
echo "5. Click it → Search box appears"
echo ""
echo "For Push Notifications:"
echo "   → Type 'push' → Select 'Push Notifications'"
echo ""
echo "For Background Modes:"
echo "   → Click '+ Capability' again"
echo "   → Type 'background' → Select 'Background Modes'"
echo "   → Expand Background Modes section"
echo "   → Check ✅ 'Remote notifications'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 Tips:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "• The search is case-insensitive"
echo "• Try partial words: 'push', 'notif', 'background', 'remote'"
echo "• If you don't see them, make sure:"
echo "  - You're in 'Signing & Capabilities' tab"
echo "  - You selected the 'Runner' TARGET (not just the project)"
echo "  - You have a Team (Apple ID) selected"
echo ""
echo "📚 For more details, see: XCODE_CAPABILITIES_DETAILED.md"

